name: logsFromNative-Example-CI

on: [push]

jobs:
  verify:
    name: Verify the Example app sources
    runs-on: windows-latest

    steps:
      - name: Ensure the cross-platform Git on Windows
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Cache
        run: cd example && npm install

      - name: Run ESLint on the sources
        run: cd example && npx eslint .

      - name: Run ESLint on the sources
        run: cd example && npx tsc --noEmit


  build-android-app:
    name: Verify the app builds for Android platform
    runs-on: windows-latest
    needs: [verify]

    steps:
      - name: Ensure the cross-platform Git on Windows
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Pull the npm dependencies
        run: cd example && npm install

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build the Android OS app
        run: cd example/android && ./gradlew assembleDebug


  build-iOS-app:
    name: Verify the app builds for iOS platform
    runs-on: macos-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install node_modules on MacOS machine
        run: cd example && npm install

      - run: cd example/ios && xcode-select -p

      - name: Install pod dependencies
        run: cd example/ios && pod install --verbose

      - name: Opening Simulator app
        run: |
          while ! open -Fn /Applications/Xcode_13.2.1.app/Contents/Developer/Applications/Simulator.app; do
            echo "Retry"
          done
          echo "Success"

      - name: Builds the iOS app
        run: cd example && npx react-native run-ios
