name: logsFromNative-Example-CI

on: [push]

jobs:
  install:
    name: Install dependencies
    runs-on: windows-latest

    steps:
      - name: Ensure the cross-platform Git on Windows
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Display tools versions
        run: npm --version;

      - name: Restore all the packages
        run: npm install

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./package/node_modules
            ./example/node_modules
          key: ${{ hashFiles('./package/package.json') }}-${{ hashFiles('./example/package.json') }}


  verify:
    name: Lint the sources
    runs-on: windows-latest
    needs: install

    steps:
      - name: Ensure the cross-platform Git on Windows
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./package/node_modules
            ./example/node_modules
          key: ${{ hashFiles('./package/package.json') }}-${{ hashFiles('./example/package.json') }}

      - name: Run ESLint on the sources
        run: cd example && npx eslint .

      - name: Run ESLint on the sources
        run: cd example && npx tsc --noEmit

      - name: Run unit tests
        run: cd example && npx jest


  test:
    name: Run the unit tests
    runs-on: windows-latest
    needs: install

    steps:
      - name: Ensure the cross-platform Git on Windows
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Pull the npm dependencies
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./package/node_modules
            ./example/node_modules
          key: ${{ hashFiles('./package/package.json') }}-${{ hashFiles('./example/package.json') }}


  build-android-app:
    name: Verify the app builds for Android platform
    runs-on: windows-latest
    needs: [install, verify]

    steps:
      - name: Ensure the cross-platform Git on Windows
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Pull the npm dependencies
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./package/node_modules
            ./example/node_modules
          key: ${{ hashFiles('./package/package.json') }}-${{ hashFiles('./example/package.json') }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build the Android OS app
        run: cd example/android && ./gradlew assembleDebug


  build-iOS-app:
    name: Verify the app builds for iOS platform
    runs-on: macos-latest
    needs: [install, verify]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install node_modules on MacOS machine
        run: cd example && npm install

      - run: cd example/ios && xcode-select -p

      - name: Install pod dependencies
        run: cd example/ios && pod install --verbose

      - name: Builds the iOS app
        run: cd example && npx react-native run-ios
